const category_data = [
  {
    label: "Utilities",
    value: "Utilities",
    subCategory: [
      { label: "Cleaning", value: "Cleaning" },
      { label: "Electricity", value: "Electricity" },
      { label: "Heat/gas", value: "Heat/gas" },
      { label: "Other", value: "Other" },
      { label: "Trash", value: "Trash" },
      { label: "TV/ Phone/ Internet", value: "TV/ Phone/ Internet" },
      { label: "Water", value: "Water" },
    ],
  },
  {
    label: "Entertainment",
    value: "Entertainment",
    subCategory: [
      { label: "Games", value: "Games" },
      { label: "Movies", value: "Movies" },
      { label: "Music", value: "Music" },
      { label: "Sports", value: "Sports" },
      { label: "Other", value: "Other" },
    ],
  },
  {
    label: "Food and drink",
    value: "Food and drink",
    subCategory: [
      { label: "Dining Out", value: "Dining Out" },
      { label: "Groceries", value: "Groceries" },
      { label: "Liquor", value: "Liquor" },
      { label: "Other", value: "Other" },
    ],
  },
  {
    label: "Home",
    value: "Home",
    subCategory: [
      { label: "Electronics", value: "Electronics" },
      { label: "Furniture", value: "Furniture" },
      { label: "Household supplies", value: "Household supplies" },
      { label: "Maintenance", value: "Maintenance" },
      { label: "Mortgage", value: "Mortgage" },
      { label: "Pets", value: "Pets" },
      { label: "Rent", value: "Rent" },
      { label: "Services", value: "Services" },
      { label: "Other", value: "Other" },
    ],
  },
  {
    label: "Transportation",
    value: "Transportation",
    subCategory: [
      { label: "Bicycle", value: "Bicycle" },
      { label: "Bus/Train", value: "Bus/Train" },
      { label: "Car", value: "Car" },
      { label: "Gas/fuel", value: "Gas/fuel" },
      { label: "Hotel", value: "Hotel" },
      { label: "Plane", value: "Plane" },
      { label: "Taxi", value: "Taxi" },
      { label: "Parking", value: "Parking" },
      { label: "Other", value: "Other" },
    ],
  },
  {
    label: "Life",
    value: "Life",
    subCategory: [
      { label: "Childcare", value: "Childcare" },
      { label: "Clothing", value: "Clothing" },
      { label: "Education", value: "Education" },
      { label: "Gifts", value: "Gifts" },
      { label: "Insurance", value: "Insurance" },
      { label: "Medical expenses", value: "Medical expenses" },
      { label: "Taxes", value: "Taxes" },
      { label: "Other", value: "Other" },
    ],
  },
  { label: "General", value: "General" },
  { label: "Salary", value: "Salary" },
  { label: "Other", value: "Other" },
];

export { category_data };
